# this will publish demo-page

name: Demo
on:
    workflow_dispatch:
    push:

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        permissions:
            contents: write
            id-token: write
            pages: write
        environment:
            name: github-pages
            url: ${{ steps.deploy.outputs.page_url }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build:docs

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./docs

            - name: Deploy
              id: deploy
              uses: actions/deploy-pages@v4
